# Generated by Django 5.2.4 on 2025-07-30 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('story', models.TextField()),
                ('source', models.CharField(choices=[('AI', 'AI Generated'), ('Human', 'Human Written')], max_length=10)),
                ('age_group', models.CharField(choices=[('4-6', '4-6 years'), ('7-12', '7-12 years'), ('13+', '13+ years')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('safety_violations', models.JSONField(blank=True, default=dict)),
                ('stereotypes_biases', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthorshipDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_source', models.CharField(choices=[('AI', 'AI Generated'), ('Human', 'Human Written')], max_length=10)),
                ('confidence_score', models.FloatField()),
                ('features', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authorship', to='stories.story')),
            ],
        ),
        migrations.CreateModel(
            name='StoryAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_count', models.IntegerField()),
                ('sentence_count', models.IntegerField()),
                ('ttr', models.FloatField()),
                ('flesch_kincaid_grade', models.FloatField()),
                ('ari_score', models.FloatField()),
                ('sentiment_label', models.CharField(max_length=20)),
                ('sentiment_score', models.FloatField()),
                ('pos_distribution', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='stories.story')),
            ],
        ),
    ]
